<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Authors>Tursunpo'lat Iskandarov</Authors>
    <Company>CUBO kompaniyasi</Company>
    <Product>Nazoratchi</Product>
  </PropertyGroup>

</Project>
